/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    testimonials: Testimonial;
    'form-submissions': FormSubmission;
    industries: Industry;
    authors: Author;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        headline: string;
        /**
         * z.B. "100% Bot-Free Guarantee"
         */
        badgeText?: string | null;
        subheadline?: string | null;
        ctaText?: string | null;
        ctaLinkType?: ('page' | 'anchor') | null;
        /**
         * z.B. /kontakt oder /services
         */
        ctaLink?: string | null;
        ctaAnchor?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        /**
         * Optional secondary button (ghost style)
         */
        secondaryCtaText?: string | null;
        /**
         * z.B. /demo oder /features
         */
        secondaryCtaLink?: string | null;
        /**
         * Configure the cards that appear in the hero grid.
         */
        bentoCards?:
          | {
              cardType: 'image' | 'screenshot' | 'stat' | 'decorative';
              cardSize?: ('small' | 'medium' | 'large') | null;
              image?: (number | null) | Media;
              statValue?: string | null;
              statLabel?: string | null;
              /**
               * Optional decorative background for the stat card
               */
              statBackgroundImage?: (number | null) | Media;
              /**
               * Small label shown above the content
               */
              cardTitle?: string | null;
              /**
               * Override the main headline when this card is active
               */
              cardHeadline?: string | null;
              /**
               * Override the main subheadline when this card is active
               */
              cardSubheadline?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        headline: string;
        subheadline?: string | null;
        /**
         * Image displayed on the right side. If empty, text will be centered.
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pageHero';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        title: string;
        introduction: string;
        services: (number | Service)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceGrid';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline: string;
        services: (number | Service)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'additionalServices';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        tagline?: string | null;
        headline: string;
        industries: (number | Industry)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'industriesGrid';
      }
    | FocusIndustriesGridBlock
    | AdditionalIndustriesBlock
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        logos?:
          | {
              logo: number | Media;
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        speed?: ('slow' | 'normal' | 'fast') | null;
        invertLogos?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoTicker';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        subheadline?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image: number | Media;
        /**
         * Add more images here to create a slideshow. The Main Image will be the first slide.
         */
        additionalImages?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        imagePosition?: ('left' | 'right') | null;
        ctaText?: string | null;
        ctaLinkType?: ('page' | 'anchor') | null;
        /**
         * e.g., /contact or /services
         */
        ctaLink?: string | null;
        ctaAnchor?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        /**
         * The actual quote content to display in the card.
         */
        quoteText?: string | null;
        authorName?: string | null;
        authorRole?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentSideBySide';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        subheadline?: string | null;
        videoFile: number | Media;
        thumbnail?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'videoBlock';
      }
    | {
        headline?: string | null;
        subheadline?: string | null;
        introText?: string | null;
        phoneNumber?: string | null;
        cardHeadline?: string | null;
        buttonText?: string | null;
        privacyText?: string | null;
        footerText?: string | null;
        /**
         * Where should contact form submissions be sent?
         */
        emailTo?: string | null;
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        items: {
          title: string;
          content: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'accordion';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richTextContent';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        /**
         * Wähle die passende Darstellungsform für den Text.
         */
        variant?: ('hint' | 'standard' | 'page') | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'textBlock';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        subheadline?: string | null;
        onboardingEnabled?: boolean | null;
        onboardingLabel?: string | null;
        onboardingPrice?: string | null;
        /**
         * Die Service-Pakete (empfohlen: 3-4 Pakete)
         */
        packages?:
          | {
              name: string;
              isRecommended?: boolean | null;
              /**
               * Mehrzeilige Eingabe möglich
               */
              openingHours: string;
              /**
               * z.B. "ab 199€/Monat" oder leer lassen
               */
              price?: string | null;
              /**
               * z.B. "zzgl. Minutenpreis"
               */
              priceNote?: string | null;
              id?: string | null;
            }[]
          | null;
        featuresHeadline?: string | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        ctaText?: string | null;
        ctaLinkType?: ('page' | 'anchor') | null;
        /**
         * z.B. /kontakt oder /services
         */
        ctaLink?: string | null;
        ctaAnchor?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingGrid';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        subheadline?: string | null;
        addons?:
          | {
              name: string;
              description?: string | null;
              /**
               * z.B. "500€" – leer lassen wenn nicht zutreffend
               */
              onetimePrice?: string | null;
              /**
               * z.B. "99€" – leer lassen wenn nicht zutreffend
               */
              monthlyPrice?: string | null;
              /**
               * z.B. "*in Verbindung mit Super 365"
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * z.B. "Alle Preise zzgl. gesetzlicher Mehrwertsteuer"
         */
        footnotes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricingAddons';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        headline?: string | null;
        subheadline?: string | null;
        postsCount?: number | null;
        ctaText?: string | null;
        ctaLinkType?: ('page' | 'anchor') | null;
        ctaLink?: string | null;
        ctaAnchor?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogTeaser';
      }
    | {
        /**
         * Appearance settings for this block
         */
        settings?: {
          theme?: ('light' | 'dark') | null;
          /**
           * Optional. Assign an anchor so navigation can link to this block.
           */
          anchorId?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        };
        postsPerPage?: number | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogPosts';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  icon?: (number | null) | Media;
  selectedIcon?: string | null;
  type?: ('main' | 'additional') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  /**
   * URL-freundlicher Name (z.B. "immobilien", "e-commerce")
   */
  slug: string;
  /**
   * Focus-Branchen werden prominent auf der Homepage dargestellt
   */
  type: 'focus' | 'additional';
  /**
   * Select a standard icon from the list
   */
  selectedIcon?:
    | (
        | 'Home'
        | 'ShoppingCart'
        | 'Car'
        | 'Store'
        | 'Heart'
        | 'Stethoscope'
        | 'Scale'
        | 'Utensils'
        | 'Hammer'
        | 'Building2'
        | 'Armchair'
        | 'Shield'
        | 'Hotel'
        | 'Building'
        | 'Factory'
        | 'Package'
        | 'Briefcase'
        | 'GraduationCap'
        | 'PhoneCall'
        | 'Wrench'
        | 'UserCheck'
        | 'TrendingUp'
        | 'RefreshCw'
        | 'CreditCard'
        | 'Users'
        | 'Gauge'
        | 'Filter'
        | 'ClipboardList'
        | 'MessageSquare'
        | 'Database'
        | 'PhoneForwarded'
        | 'Smile'
      )
    | null;
  /**
   * Upload a custom icon image if you don't want to use a standard icon
   */
  icon?: (number | null) | Media;
  /**
   * Kurze Beschreibung für Übersichtskarten (1-2 Sätze)
   */
  description?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Großes Bild für die Branchen-Detail-Seite
   */
  featuredImage?: (number | null) | Media;
  /**
   * Detaillierte Beschreibung der Branchenlösung
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Liste der Vorteile für diese Branche
   */
  benefits?:
    | {
        title: string;
        description?: string | null;
        icon?:
          | (
              | 'Check'
              | 'Star'
              | 'Zap'
              | 'Shield'
              | 'Phone'
              | 'MessageSquare'
              | 'Calendar'
              | 'Clock'
              | 'PhoneCall'
              | 'Wrench'
              | 'UserCheck'
              | 'TrendingUp'
              | 'RefreshCw'
              | 'CreditCard'
              | 'Gauge'
              | 'Filter'
              | 'ClipboardList'
              | 'Database'
              | 'PhoneForwarded'
              | 'Smile'
              | 'Users'
              | 'Headset'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Überschreibt den Standard-Titel für Suchmaschinen
   */
  metaTitle?: string | null;
  /**
   * Beschreibung für Suchmaschinen (max. 160 Zeichen)
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FocusIndustriesGridBlock".
 */
export interface FocusIndustriesGridBlock {
  /**
   * Small text above the headline (optional)
   */
  tagline?: string | null;
  headline?: string | null;
  introduction?: string | null;
  /**
   * Select focus industries to display (only industries with type "focus" will be shown properly)
   */
  industries?: (number | Industry)[] | null;
  settings?: {
    theme?: ('dark' | 'light') | null;
    showLink?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'focusIndustriesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdditionalIndustriesBlock".
 */
export interface AdditionalIndustriesBlock {
  headline?: string | null;
  /**
   * Select additional industries to display in compact icon list
   */
  industries?: (number | Industry)[] | null;
  settings?: {
    theme?: ('dark' | 'light') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'additionalIndustries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  company?: string | null;
  role?: string | null;
  quote: string;
  avatar?: (number | null) | Media;
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  message?: string | null;
  source?: string | null;
  company?: string | null;
  position?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-freundlicher Name (z.B. "mein-erster-beitrag")
   */
  slug: string;
  /**
   * Wird in Übersichten und Teasern angezeigt
   */
  excerpt?: string | null;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | Author;
  publishedAt: string;
  /**
   * Geschätzte Lesezeit in Minuten
   */
  readingTime?: number | null;
  /**
   * Für Suchmaschinen (leer = Titel wird verwendet)
   */
  metaTitle?: string | null;
  /**
   * 1-2 vollständige Sätze für Suchmaschinen, z.B. "Erfahren Sie, wie KI Ihren Kundenservice verbessert." (leer = Kurzbeschreibung wird verwendet)
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              badgeText?: T;
              subheadline?: T;
              ctaText?: T;
              ctaLinkType?: T;
              ctaLink?: T;
              ctaAnchor?: T;
              secondaryCtaText?: T;
              secondaryCtaLink?: T;
              bentoCards?:
                | T
                | {
                    cardType?: T;
                    cardSize?: T;
                    image?: T;
                    statValue?: T;
                    statLabel?: T;
                    statBackgroundImage?: T;
                    cardTitle?: T;
                    cardHeadline?: T;
                    cardSubheadline?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageHero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        serviceGrid?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              title?: T;
              introduction?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        additionalServices?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        industriesGrid?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              tagline?: T;
              headline?: T;
              industries?: T;
              id?: T;
              blockName?: T;
            };
        focusIndustriesGrid?: T | FocusIndustriesGridBlockSelect<T>;
        additionalIndustries?: T | AdditionalIndustriesBlockSelect<T>;
        testimonials?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        logoTicker?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    id?: T;
                  };
              speed?: T;
              invertLogos?: T;
              id?: T;
              blockName?: T;
            };
        contentSideBySide?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              subheadline?: T;
              content?: T;
              image?: T;
              additionalImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              imagePosition?: T;
              ctaText?: T;
              ctaLinkType?: T;
              ctaLink?: T;
              ctaAnchor?: T;
              quoteText?: T;
              authorName?: T;
              authorRole?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              subheadline?: T;
              videoFile?: T;
              thumbnail?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              introText?: T;
              phoneNumber?: T;
              cardHeadline?: T;
              buttonText?: T;
              privacyText?: T;
              footerText?: T;
              emailTo?: T;
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accordion?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextContent?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              content?: T;
              id?: T;
              blockName?: T;
            };
        textBlock?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              variant?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        pricingGrid?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              subheadline?: T;
              onboardingEnabled?: T;
              onboardingLabel?: T;
              onboardingPrice?: T;
              packages?:
                | T
                | {
                    name?: T;
                    isRecommended?: T;
                    openingHours?: T;
                    price?: T;
                    priceNote?: T;
                    id?: T;
                  };
              featuresHeadline?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLinkType?: T;
              ctaLink?: T;
              ctaAnchor?: T;
              id?: T;
              blockName?: T;
            };
        pricingAddons?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              subheadline?: T;
              addons?:
                | T
                | {
                    name?: T;
                    description?: T;
                    onetimePrice?: T;
                    monthlyPrice?: T;
                    note?: T;
                    id?: T;
                  };
              footnotes?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogTeaser?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              headline?: T;
              subheadline?: T;
              postsCount?: T;
              ctaText?: T;
              ctaLinkType?: T;
              ctaLink?: T;
              ctaAnchor?: T;
              id?: T;
              blockName?: T;
            };
        blogPosts?:
          | T
          | {
              settings?:
                | T
                | {
                    theme?: T;
                    anchorId?: T;
                  };
              postsPerPage?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FocusIndustriesGridBlock_select".
 */
export interface FocusIndustriesGridBlockSelect<T extends boolean = true> {
  tagline?: T;
  headline?: T;
  introduction?: T;
  industries?: T;
  settings?:
    | T
    | {
        theme?: T;
        showLink?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdditionalIndustriesBlock_select".
 */
export interface AdditionalIndustriesBlockSelect<T extends boolean = true> {
  headline?: T;
  industries?: T;
  settings?:
    | T
    | {
        theme?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  selectedIcon?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  role?: T;
  quote?: T;
  avatar?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  source?: T;
  company?: T;
  position?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  selectedIcon?: T;
  icon?: T;
  description?: T;
  order?: T;
  featuredImage?: T;
  content?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage global site settings like logo, navigation, and footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in header (dark) and footer (white) - styled automatically.
   */
  logo: number | Media;
  awardEnabled?: boolean | null;
  awardImage?: (number | null) | Media;
  awardTitle?: string | null;
  /**
   * Supports bold, italic, lists, etc.
   */
  awardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Drag & drop to reorder menu items.
   */
  navigation?:
    | {
        label: string;
        linkType?: ('page' | 'anchor') | null;
        /**
         * e.g., /about or /services
         */
        pageLink?: string | null;
        /**
         * Select an anchor defined on a block
         */
        anchorLink?: ('contact-form' | 'services' | 'testimonials' | 'video' | 'industries' | 'suite') | null;
        id?: string | null;
      }[]
    | null;
  ctaType?: ('link' | 'phone') | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  /**
   * Format: +49 30 123456789
   */
  ctaPhone?: string | null;
  phoneNumber?: string | null;
  email?: string | null;
  footerText?: string | null;
  /**
   * z.B. https://instagram.com/avanti.cx
   */
  socialInstagram?: string | null;
  /**
   * z.B. https://linkedin.com/company/avanti
   */
  socialLinkedin?: string | null;
  companyName?: string | null;
  /**
   * Mehrzeilige Adresse für den Footer
   */
  companyAddress?: string | null;
  /**
   * Füge PDF-Dokumente hinzu, die als Download verfügbar sein sollen
   */
  legalDocuments?:
    | {
        /**
         * z.B. "Nutzungsbedingungen" oder "AGB"
         */
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Pfad zur Impressum-Seite, z.B. /impressum
   */
  imprintLink?: string | null;
  /**
   * Pfad zur Datenschutz-Seite, z.B. /datenschutz
   */
  privacyLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  awardEnabled?: T;
  awardImage?: T;
  awardTitle?: T;
  awardDescription?: T;
  navigation?:
    | T
    | {
        label?: T;
        linkType?: T;
        pageLink?: T;
        anchorLink?: T;
        id?: T;
      };
  ctaType?: T;
  ctaText?: T;
  ctaLink?: T;
  ctaPhone?: T;
  phoneNumber?: T;
  email?: T;
  footerText?: T;
  socialInstagram?: T;
  socialLinkedin?: T;
  companyName?: T;
  companyAddress?: T;
  legalDocuments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  imprintLink?: T;
  privacyLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}